module.exports = {
  fetchCategoriesSuccess: 'FETCH_CATEGORIES_SUCCESS',
  deleteCategorySuccess: 'DELETE_CATEGORY_SUCCESS',
  createCategorySuccess: 'CREATE_CATEGORY_SUCCESS',
  editCategorySuccess: 'EDIT_CATEGORY_SUCCESS',
  fetchCategories: 'FETCH_CATEGORIES',
  beginAjaxCall: 'BEGIN_AJAX_CALL',
  expandSidebar: 'EXPAND_SIDEBAR',
  loginSuccess: 'LOGIN_SUCCESS',
  authenticateSuccess: 'AUTHENTICATE_SUCCESS',
  mockSuccess: 'MOCK_SUCCESS',
  toggleCategoryPrivacySuccess: 'TOGGLE_CATEGORY_PRIVACY_SUCCESS',
  editCategoryCommandSuccess: 'EDIT_CATEGORY_COMMAND_SUCCESS',
  createCategoryCommandsSuccess: 'CREATE_CATEGORY_COMMAND_SUCCESS',
  deleteCategoryCommandSuccess: 'DELETE_CATEGORY_COMMAND_SUCCESS',
};
